# Generated by Django 5.1.3 on 2024-11-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_alter_notification_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("message", "채팅 메시지 알림"),
                    ("reserved", "예약 확정 알림"),
                    ("review", "리뷰 등록 알림"),
                    ("estimation", "견적 알림"),
                    ("estimation_request", "견적 요청 알림"),
                    ("usage", "이용 완료 알림"),
                    ("schedule", "일정 알림"),
                ],
                max_length=20,
            ),
        ),
    ]
