# Generated by Django 5.1.3 on 2024-11-14 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reservations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rating",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "score",
                    models.DecimalField(
                        choices=[
                            (0.5, 0.5),
                            (1, 1),
                            (1.5, 1.5),
                            (2, 2),
                            (2.5, 2.5),
                            (3, 3),
                            (3.5, 3.5),
                            (4, 4),
                            (4.5, 4.5),
                            (5, 5),
                        ],
                        decimal_places=1,
                        max_digits=2,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reservation",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="reservations.reservation"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=50)),
                ("content", models.TextField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reservation",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="reservations.reservation"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReviewImages",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to="images/reviews/")),
                ("review", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="reviews.review")),
            ],
        ),
    ]
