# Generated by Django 5.1.3 on 2024-11-14 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="score",
            field=models.DecimalField(
                choices=[
                    (0.5, 0.5),
                    (1, 1),
                    (1.5, 1.5),
                    (2, 2),
                    (2.5, 2.5),
                    (3, 3),
                    (3.5, 3.5),
                    (4, 4),
                    (4.5, 4.5),
                    (5, 5),
                ],
                decimal_places=1,
                default=0,
                max_digits=2,
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Rating",
        ),
    ]
