# Generated by Django 5.1.3 on 2024-11-14 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_review_score_delete_rating"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="score",
            new_name="rating",
        ),
    ]
