# Generated by Django 5.1.3 on 2024-11-16 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0003_rename_score_review_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="title",
        ),
        migrations.AlterField(
            model_name="reviewimages",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/reviews/"),
        ),
    ]
