# Generated by Django 5.1.3 on 2024-12-09 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0005_alter_review_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewimages",
            name="review",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="images", to="reviews.review"
            ),
        ),
    ]
