# Generated by Django 5.1.3 on 2024-11-14 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("expert", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="expert",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="career",
            name="expert",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="expert.expert"),
        ),
        migrations.AddField(
            model_name="expertimage",
            name="expert",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="expert.expert"),
        ),
        migrations.AddField(
            model_name="service",
            name="expert",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="expert.expert"),
        ),
    ]
