# Generated by Django 5.1.3 on 2024-11-16 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expert", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="expert",
        ),
        migrations.RenameField(
            model_name="expert",
            old_name="profile_image",
            new_name="expert_image",
        ),
        migrations.AddField(
            model_name="expert",
            name="service",
            field=models.CharField(
                choices=[("mc", "MC"), ("snap", "스냅"), ("singer", "가수"), ("video", "영상")],
                default="",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="expert",
            name="standard_charge",
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name="ExpertImage",
        ),
        migrations.DeleteModel(
            name="Service",
        ),
    ]
