# Generated by Django 5.1.3 on 2024-11-28 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expert", "0005_alter_expert_available_location_alter_expert_service"),
    ]

    operations = [
        migrations.AlterField(
            model_name="career",
            name="expert",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="careers", to="expert.expert"
            ),
        ),
    ]
