# Generated by Django 5.1.3 on 2024-11-13 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("estimations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "진행중"),
                            ("confirmed", "예약확정"),
                            ("cancel", "예약취소"),
                            ("cancelling", "취소중"),
                            ("completed", "완료"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "estimation",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="estimations.estimation"),
                ),
            ],
        ),
    ]
