# Generated by Django 5.1.3 on 2024-12-06 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0002_cancelmanager"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[("confirmed", "예약 확정"), ("canceled", "예약 취소"), ("completed", "서비스 완료")],
                max_length=20,
            ),
        ),
    ]
