# Generated by Django 5.1.3 on 2024-12-09 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estimations", "0009_alter_estimationsrequest_prefer_gender"),
        ("reservations", "0003_alter_reservation_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cancelmanager",
            name="reservation",
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="reservations.reservation"),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="estimation",
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="estimations.estimation"),
        ),
    ]
