# Generated by Django 5.1.3 on 2024-12-06 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_prefer_location_alter_user_prefer_service"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to="images/users/profile/"),
        ),
    ]
