# Generated by Django 5.1.3 on 2024-11-15 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estimations", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estimationsrequest",
            name="prefer_gender",
            field=models.CharField(choices=[("M", "남성"), ("F", "여성")], max_length=20),
        ),
    ]
