# Generated by Django 5.1.3 on 2024-11-19 06:49

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("estimations", "0004_alter_estimationsrequest_prefer_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estimationsrequest",
            name="service_list",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[("mc", "MC"), ("snap", "스냅"), ("singer", "가수"), ("video", "영상")], max_length=30
            ),
        ),
    ]
