# Generated by Django 5.1.3 on 2024-12-06 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estimations", "0007_alter_estimation_location_alter_estimation_service_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="estimationsrequest",
            name="is_reception",
            field=models.BooleanField(default=False),
        ),
    ]
