# Generated by Django 5.1.3 on 2024-12-09 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estimations", "0008_estimationsrequest_is_reception"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estimationsrequest",
            name="prefer_gender",
            field=models.CharField(choices=[("M", "남성"), ("F", "여성"), ("ANY", "상관없음")], max_length=20),
        ),
    ]
