# Generated by Django 5.1.3 on 2024-12-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estimations", "0009_alter_estimationsrequest_prefer_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="estimation",
            name="description",
            field=models.TextField(default="empty"),
            preserve_default=False,
        ),
    ]
