# Generated by Django 5.1.3 on 2024-11-27 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_initial"),
        ("estimations", "0007_alter_estimation_location_alter_estimation_service_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="request",
            field=models.OneToOneField(
                default=1, on_delete=django.db.models.deletion.RESTRICT, to="estimations.estimationsrequest"
            ),
            preserve_default=False,
        ),
    ]
