# Generated by Django 5.1.3 on 2024-12-09 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_chatroom_request"),
        ("estimations", "0009_alter_estimationsrequest_prefer_gender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatroom",
            name="request",
        ),
        migrations.AddField(
            model_name="chatroom",
            name="estimation",
            field=models.OneToOneField(
                default=1, on_delete=django.db.models.deletion.RESTRICT, to="estimations.estimation"
            ),
            preserve_default=False,
        ),
    ]
