# django_deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: stop.kr.ncr.ntruss.com/oz-collabo-repo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: POSTGRES_HOST
          value: "db"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          value: "oz_collabo"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
        - name: REDIS_HOST
          value: "redis-service"
        - name: REDIS_PORT
          value: "6379"
        volumeMounts:
        - name: static-volume
          mountPath: /app/src/static
        - name: media-volume
          mountPath: /app/src/media
      volumes:
      - name: static-volume
        emptyDir: {}
      - name: media-volume
        emptyDir: {}
      imagePullSecrets:
        - name: amuguna